### ISSUE TITLE
Error using PeakList function in a version of 2017a

### ISSUE THREAD

**Issue by Salonigupta3** [glerny/Finnee2016#1]
I recently tried this toolbox for data analysis of LC-MS/MS Data. I executed codes for CE-TOFMS Urine Sample Dataset but I'm getting an error while using **PeakList** function.

>>  **myPeakList=PeakList(myFinnee.Datasets{5},100,0.1,5);**
     Struct contents reference from a non-struct array object.

     Error in PeakList (line 111)
                    IdN = findCloser(obj.LstPIP{1}{ii}.FOM(7),obj.Noise.Data(:,1));

Can anyone please give an insight on how to debug this error.
Thank you in advance!

**Comment by glerny** [comment]
Hello,

The measured background noise is not copied from Dataset 3 to dataset 5. I'll correct that in the next commit. At the moment add the following line before creating the PeakList:

` myFinnee.Datasets{5}.Noise = myFinnee.Datasets{3}.AddInfo.Peak2PeakNoise;`

That should work

Guillaume

**Comment by Salonigupta3** [comment]
Thank you sir.
And yes that worked.
