### ISSUE TITLE
Error: Undefined function or variable 'compression' while creating Finnee object.

### ISSUE THREAD

**Issue by Salonigupta3** [glerny/Finnee2016#2]
Hey everyone!

Can anyone please tell me why I'm getting these error while creating finnee object for my own dataset(mzML file)?

      PFinnee=Finnee;
      Undefined function or variable 'compression'.

      Error in Finnee/Finnee/domzML2Finnee (line 453)
                            switch compression

      Error in Finnee (line 197)
            [obj, MSn]      = domzML2Finnee(obj);

I have already created a Finnee object using CE-TOFMS dataset but when I use a dataset of my own, it is showing these error.
Can anyone please help me debug these error?
Thanks in advance!

**Comment by glerny** [comment]
The most likely reason is that the scans in the mzML file does not contain a field "compression". You can try to generate new mzML files using msConvert (http://proteowizard.sourceforge.net/tools.shtml). It is also possible that your data are not obtained with high resolution MS (time of flight, orbitrap), in this case Finnee will not be of great help. If this is the case, you may want to give a try to OpenMS (https://www.openms.de/). If you want you can attach the mzML file and I can have a look, but that will probably not be this week.

Best

Guillaume

**Comment by Salonigupta3** [comment]
Thank you sir for the reply.
Yes, I think its due to lack of compression field in mzML file. I'll sort that out now.

Sincerely

Saloni Gupta

**Comment by Salonigupta3** [comment]
Sir, can you tell which one is required as there are many options for compression? 
I have obtained dataset using Q-TOF.
https://drive.google.com/file/d/1Sc-eOVFwR-u9iHBDj5635Q4a8pt7zK5D/view?usp=sharing

The link to the options is above, please can you have a look at it and tell which compression option to select?
This options are displayed using msConvert.
If the link is not working,this are the options: 
1) Use zlib compression
2) Use numpress linear compression
3) Use numpress short logged float compression
4) Use numpress positive integer compression

Also there are other few options, can you tell which selection of options would be good for analysis using finnee?
It would be a very great help. Thank you in advance!

**Comment by glerny** [comment]
I will use option 1. See attached my default configuration.
![default MSConvert](https://user-images.githubusercontent.com/11735178/88308232-b5177c80-cd04-11ea-8d90-40a277029350.jpg)
