### ISSUE TITLE
How to set intensity threshold for extracted ion profile trace object?

### ISSUE THREAD

**Issue by Salonigupta3** [glerny/Finnee2016#3]
I'm using finnee toolbox for data analysis using CE-TOFMS Urine dataset.

I was extracting some Extracted Ion Profile for a range of mz when I wanted to set an intensity threshold so that if at some mz, intensity is below that threshold it skips that and detect only that mz whose peak is greater than in threshold same as in xcms.

I tried this:
>>m1=myFinnee.Datasets{2}.getProfile(115.9221);
for i=1:1265
      if m2(i,2)<1000
        m2(i,2)=0;
    end
end
>>for i=1:1265
    m1.Data(i,2)=m2(i,2);
     end
**In class 'Trace', no set method is defined for Dependent property 'Data'.  A Dependent property needs a set method to assign its value.**

Can anyone please help me achieve this goal?
Thanks in advance!

**Comment by glerny** [comment]
Ok,  first you should not used an m/z interval, for example
`m1 = myFinnee.Datasets{2}.getProfile([115.920 115.924])`
the interval should be optimised for your instrument mass resolution.

The variable Data in trace is dependent so cannot be changed. You can use:
`>> 
MS = m1.Data;
>> figure, plot(MS(:,1) , MS(:,2))
>> Ix = MS(:,2) <= 1000;
>> MS(Ix, 2) = 0;
>> figure, plot(MS(:,1) , MS(:,2))`

or shorter
`MS(MS(:,2) <= 1000, 2) = 0`


![example](https://user-images.githubusercontent.com/11735178/88310043-20fae480-cd07-11ea-97f0-ab93d58b4bb9.jpg)
